const DEMO_BLOGS = [
    {
        id: 1,
        title: "Understanding Financial Statements",
        slug: "understanding-financial-statements",
        category: "back-to-basics",
        excerpt: "A comprehensive guide to reading and interpreting balance sheets, income statements, and cash flow statements.",
        featured_image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-10",
        read_time: 5,
        content: "<h2>Introduction to Financial Statements</h2><p>Financial statements are the backbone of financial analysis...</p>"
    },
    {
        id: 2,
        title: "Understanding Financial Statements",
        slug: "understanding-financial-statements",
        category: "back-to-basics",
        excerpt: "A comprehensive guide to reading and interpreting balance sheets, income statements, and cash flow statements.",
        featured_image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-10",
        read_time: 5,
        content: "<h2>Introduction to Financial Statements</h2><p>Financial statements are the backbone of financial analysis...</p>"
    },
    {
        id: 3,
        title: "What is Market Capitalization?",
        slug: "what-is-market-capitalization",
        category: "back-to-basics",
        excerpt: "Learn the fundamentals of market cap and why it matters for investors.",
        featured_image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-08",
        read_time: 4,
        content: "<h2>Market Capitalization Explained</h2><p>Market capitalization is a key metric...</p>"
    },
    {
        id: 4,
        title: "IPO Basics: What Every Investor Should Know",
        slug: "ipo-basics",
        category: "back-to-basics",
        excerpt: "Everything you need to know about Initial Public Offerings before investing.",
        featured_image: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-05",
        read_time: 6,
        content: "<h2>IPO Fundamentals</h2><p>An Initial Public Offering is when a company...</p>"
    },
    {
        id: 5,
        title: "Tata Motors' Turnaround Strategy",
        slug: "tata-motors-turnaround",
        category: "case-studies",
        excerpt: "Deep dive into how Tata Motors transformed from losses to profitability through strategic decisions.",
        featured_image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-12",
        read_time: 8,
        content: "<h2>The Tata Motors Story</h2><p>In 2019, Tata Motors faced significant challenges...</p>"
    },
    {
        id: 6,
        title: "Reliance Jio: Disrupting Indian Telecom",
        slug: "reliance-jio-disruption",
        category: "case-studies",
        excerpt: "How Reliance Jio changed the Indian telecom landscape with aggressive pricing and digital strategy.",
        featured_image: "https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-09",
        read_time: 10,
        content: "<h2>Jio's Market Entry</h2><p>When Reliance Jio launched in 2016...</p>"
    },
    {
        id: 7,
        title: "Zomato's IPO Journey",
        slug: "zomato-ipo-journey",
        category: "case-studies",
        excerpt: "Analyzing Zomato's path to becoming India's first unicorn food-tech IPO.",
        featured_image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-06",
        read_time: 7,
        content: "<h2>Zomato Goes Public</h2><p>Zomato's IPO in July 2021 marked a milestone...</p>"
    },
    {
        id: 8,
        title: "HDFC Bank: A Banking Giant Analysis",
        slug: "hdfc-bank-analysis",
        category: "stock-analysis",
        excerpt: "Comprehensive analysis of HDFC Bank's financials, growth prospects, and market position.",
        featured_image: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-11",
        read_time: 9,
        content: "<h2>HDFC Bank Overview</h2><p>HDFC Bank is India's largest private sector bank...</p>"
    },
    {
        id: 9,
        title: "Infosys Q4 Results Breakdown",
        slug: "infosys-q4-results",
        category: "stock-analysis",
        excerpt: "Detailed breakdown of Infosys quarterly results and future guidance.",
        featured_image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-07",
        read_time: 6,
        content: "<h2>Q4 Performance</h2><p>Infosys reported strong Q4 results...</p>"
    },
    {
        id: 10,
        title: "Asian Paints: Valuation Check",
        slug: "asian-paints-valuation",
        category: "stock-analysis",
        excerpt: "Is Asian Paints overvalued? A deep dive into the paint giant's metrics.",
        featured_image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-04",
        read_time: 7,
        content: "<h2>Valuation Analysis</h2><p>Asian Paints has been a market favorite...</p>"
    },
    {
        id: 11,
        title: "Day 1: Setting Investment Goals",
        slug: "day-1-investment-goals",
        category: "100-days-challenge",
        excerpt: "Starting the 100-day journey to financial literacy. Today: defining clear investment objectives.",
        featured_image: "https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-13",
        read_time: 4,
        content: "<h2>Day 1 Challenge</h2><p>Welcome to the 100 Days Challenge...</p>"
    },
    {
        id: 12,
        title: "Day 15: Understanding Risk Tolerance",
        slug: "day-15-risk-tolerance",
        category: "100-days-challenge",
        excerpt: "Assessing your risk appetite and how it shapes your investment strategy.",
        featured_image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-10",
        read_time: 5,
        content: "<h2>Risk Assessment</h2><p>Understanding risk is crucial...</p>"
    },
    {
        id: 13,
        title: "Day 30: Portfolio Diversification",
        slug: "day-30-portfolio-diversification",
        category: "100-days-challenge",
        excerpt: "Why putting all eggs in one basket is risky. Learn diversification strategies.",
        featured_image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-08",
        read_time: 6,
        content: "<h2>Diversification Matters</h2><p>Don't put all your eggs in one basket...</p>"
    },
    {
        id: 14,
        title: "Walmart-Flipkart Deal: $16B Acquisition",
        slug: "walmart-flipkart-deal",
        category: "ma-diaries",
        excerpt: "Breaking down Walmart's mega acquisition of Flipkart and its impact on Indian e-commerce.",
        featured_image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-12",
        read_time: 8,
        content: "<h2>The Deal</h2><p>In 2018, Walmart acquired 77% stake in Flipkart...</p>"
    },
    {
        id: 15,
        title: "Tata-Air India Merger Analysis",
        slug: "tata-air-india-merger",
        category: "ma-diaries",
        excerpt: "Tata Group's acquisition of Air India: Strategic rationale and challenges ahead.",
        featured_image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-09",
        read_time: 9,
        content: "<h2>Air India Returns Home</h2><p>After 69 years, Air India returns to Tata...</p>"
    },
    {
        id: 16,
        title: "HDFC-HDFC Bank Merger: Creating a Giant",
        slug: "hdfc-merger",
        category: "ma-diaries",
        excerpt: "The largest merger in Indian corporate history. What it means for stakeholders.",
        featured_image: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-05",
        read_time: 10,
        content: "<h2>Historic Merger</h2><p>HDFC Ltd and HDFC Bank announced their merger...</p>"
    },
    {
        id: 17,
        title: "blah",
        slug: "hdfc-merger",
        category: "ma-diaries",
        excerpt: "The largest merger in Indian corporate history. What it means for stakeholders.",
        featured_image: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&h=600&fit=crop",
        author: "Pushkar",
        published_at: "2024-02-05",
        read_time: 10,
        content: "<h2>Historic Merger</h2><p>HDFC Ltd and HDFC Bank announced their merger...</p>"
    }
];

window.DEMO_BLOGS = DEMO_BLOGS;
